version: '3'
services:
    flowise:
        image: flowise
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            FLOWISE_USERNAME: ${FLOWISE_USERNAME}
            FLOWISE_PASSWORD: ${FLOWISE_PASSWORD}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
            FUTUREBOT_API_SECRET: ${FUTUREBOT_API_SECRET}
            LAMBDA_URL: ${LAMBDA_URL}
            FUTUREBOT_ID: ${FUTUREBOT_ID}
            INTERNAL_CHATFLOW_ID: ${INTERNAL_CHATFLOW_ID}
            API_TEST_ID: ${API_TEST_ID}
            STORAGE_TYPE: ${STORAGE_TYPE}
            S3_STORAGE_BUCKET_NAME: ${S3_STORAGE_BUCKET_NAME}
            S3_STORAGE_ACCESS_KEY_ID: ${S3_STORAGE_ACCESS_KEY_ID}
            S3_STORAGE_SECRET_ACCESS_KEY: ${S3_STORAGE_SECRET_ACCESS_KEY}
            S3_STORAGE_REGION: ${S3_STORAGE_REGION}
            APIKEY_PATH: '/root/.flowise'
            SECRETKEY_PATH: '/root/.flowise'
            DATABASE_PATH: '/root/.flowise'
            LOG_PATH: '/root/.flowise/logs'
        ports:
            - '3000:3000'
        volumes:
            - '/root/.flowise:/root/.flowise'
        restart: always
